-- ================================================================
-- SEED HSK DICTIONARY - vocabularies table
-- HSK 1-3 comprehensive vocabulary with examples
-- Run: docker cp ... chinese_app_db:/dict_seed.sql
-- Then: docker exec -i chinese_app_db psql -U postgres -d chinese_app -f /dict_seed.sql
-- ================================================================

-- Upsert: chỉ thêm từ chưa có, không xóa dữ liệu cũ
INSERT INTO vocabularies (simplified, traditional, pinyin, meaning_vi, meaning_en, hsk_level, examples)
VALUES

-- ========== HSK 1 ==========
('你好','你好','nǐ hǎo','Xin chào','Hello',1,'[{"cn":"你好！很高兴认识你。","py":"Nǐ hǎo! Hěn gāoxìng rènshi nǐ.","vi":"Xin chào! Rất vui được gặp bạn."}]'),
('谢谢','謝謝','xiè xie','Cảm ơn','Thank you',1,'[{"cn":"谢谢你帮助我。","py":"Xièxiè nǐ bāngzhù wǒ.","vi":"Cảm ơn bạn đã giúp tôi."}]'),
('再见','再見','zài jiàn','Tạm biệt','Goodbye',1,'[{"cn":"再见，明天见！","py":"Zàijiàn, míngtiān jiàn!","vi":"Tạm biệt, ngày mai gặp lại!"}]'),
('对不起','對不起','duì bu qǐ','Xin lỗi','Sorry',1,'[{"cn":"对不起，我来晚了。","py":"Duìbuqǐ, wǒ lái wǎn le.","vi":"Xin lỗi, tôi đến muộn."}]'),
('没关系','沒關係','méi guān xi','Không sao','It is okay',1,'[{"cn":"没关系，不用担心。","py":"Méiguānxi, bùyòng dānxīn.","vi":"Không sao, đừng lo."}]'),
('我','我','wǒ','Tôi','I / Me',1,'[{"cn":"我是越南人。","py":"Wǒ shì Yuènán rén.","vi":"Tôi là người Việt Nam."}]'),
('你','你','nǐ','Bạn','You',1,'[{"cn":"你叫什么名字？","py":"Nǐ jiào shénme míngzì?","vi":"Bạn tên là gì?"}]'),
('他','他','tā','Anh ấy','He',1,'[{"cn":"他是我的老师。","py":"Tā shì wǒ de lǎoshī.","vi":"Anh ấy là giáo viên của tôi."}]'),
('她','她','tā','Cô ấy','She',1,'[{"cn":"她很漂亮。","py":"Tā hěn piàoliang.","vi":"Cô ấy rất đẹp."}]'),
('我们','我們','wǒ men','Chúng tôi','We',1,'[{"cn":"我们一起去吃饭吧。","py":"Wǒmen yīqǐ qù chīfàn ba.","vi":"Chúng ta cùng đi ăn cơm nhé."}]'),
('是','是','shì','Là','To be',1,'[{"cn":"我是学生。","py":"Wǒ shì xuéshēng.","vi":"Tôi là học sinh."}]'),
('不','不','bù','Không','No / Not',1,'[{"cn":"我不喜欢吃辣。","py":"Wǒ bù xǐhuān chī là.","vi":"Tôi không thích ăn cay."}]'),
('有','有','yǒu','Có','To have',1,'[{"cn":"我有两个妹妹。","py":"Wǒ yǒu liǎng gè mèimei.","vi":"Tôi có hai em gái."}]'),
('在','在','zài','Ở, đang','To be at',1,'[{"cn":"我在家学习。","py":"Wǒ zài jiā xuéxí.","vi":"Tôi đang học ở nhà."}]'),
('好','好','hǎo','Tốt, khỏe','Good',1,'[{"cn":"今天天气很好。","py":"Jīntiān tiānqì hěn hǎo.","vi":"Hôm nay thời tiết rất đẹp."}]'),
('大','大','dà','To, lớn','Big',1,'[{"cn":"北京是一个很大的城市。","py":"Běijīng shì yīgè hěn dà de chéngshì.","vi":"Bắc Kinh là một thành phố rất lớn."}]'),
('小','小','xiǎo','Nhỏ','Small',1,'[{"cn":"这只猫很小。","py":"Zhè zhī māo hěn xiǎo.","vi":"Con mèo này rất nhỏ."}]'),
('多','多','duō','Nhiều','Many',1,'[{"cn":"今天有很多人。","py":"Jīntiān yǒu hěn duō rén.","vi":"Hôm nay có rất nhiều người."}]'),
('少','少','shǎo','Ít','Few',1,'[{"cn":"这里的人很少。","py":"Zhèlǐ de rén hěn shǎo.","vi":"Ở đây có rất ít người."}]'),
('很','很','hěn','Rất','Very',1,'[{"cn":"这道菜很好吃。","py":"Zhè dào cài hěn hǎochī.","vi":"Món ăn này rất ngon."}]'),
('人','人','rén','Người','Person',1,'[{"cn":"他是一个好人。","py":"Tā shì yīgè hǎo rén.","vi":"Anh ấy là người tốt."}]'),
('学生','學生','xué shēng','Học sinh','Student',1,'[{"cn":"我是大学生。","py":"Wǒ shì dàxuéshēng.","vi":"Tôi là sinh viên đại học."}]'),
('老师','老師','lǎo shī','Giáo viên','Teacher',1,'[{"cn":"我的老师很亲切。","py":"Wǒ de lǎoshī hěn qīnqiè.","vi":"Giáo viên của tôi rất thân thiện."}]'),
('朋友','朋友','péng yǒu','Bạn bè','Friend',1,'[{"cn":"他是我的好朋友。","py":"Tā shì wǒ de hǎo péngyǒu.","vi":"Anh ấy là bạn tốt của tôi."}]'),
('爸爸','爸爸','bà ba','Bố, Ba','Father',1,'[{"cn":"我爸爸每天早起。","py":"Wǒ bàba měitiān zǎoqǐ.","vi":"Bố tôi dậy sớm mỗi ngày."}]'),
('妈妈','媽媽','mā ma','Mẹ','Mother',1,'[{"cn":"妈妈做的饭最好吃。","py":"Māma zuò de fàn zuì hǎochī.","vi":"Cơm mẹ nấu ngon nhất."}]'),
('哥哥','哥哥','gē ge','Anh trai','Older brother',1,'[{"cn":"我哥哥比我大三岁。","py":"Wǒ gēge bǐ wǒ dà sān suì.","vi":"Anh trai tôi hơn tôi ba tuổi."}]'),
('姐姐','姐姐','jiě jie','Chị gái','Older sister',1,'[{"cn":"我姐姐在北京工作。","py":"Wǒ jiějie zài Běijīng gōngzuò.","vi":"Chị gái tôi làm việc tại Bắc Kinh."}]'),
('妹妹','妹妹','mèi mèi','Em gái','Younger sister',1,'[{"cn":"我妹妹喜欢画画。","py":"Wǒ mèimei xǐhuān huàhuà.","vi":"Em gái tôi thích vẽ."}]'),
('弟弟','弟弟','dì di','Em trai','Younger brother',1,'[{"cn":"弟弟在上小学。","py":"Dìdi zài shàng xiǎoxué.","vi":"Em trai đang học tiểu học."}]'),
('家','家','jiā','Nhà, gia đình','Home / Family',1,'[{"cn":"我爱我的家。","py":"Wǒ ài wǒ de jiā.","vi":"Tôi yêu gia đình tôi."}]'),
('学校','學校','xué xiào','Trường học','School',1,'[{"cn":"学校明天放假。","py":"Xuéxiào míngtiān fàngjià.","vi":"Ngày mai trường nghỉ."}]'),
('中国','中國','zhōng guó','Trung Quốc','China',1,'[{"cn":"我想去中国旅游。","py":"Wǒ xiǎng qù Zhōngguó lǚyóu.","vi":"Tôi muốn đi du lịch Trung Quốc."}]'),
('北京','北京','běi jīng','Bắc Kinh','Beijing',1,'[{"cn":"北京是中国的首都。","py":"Běijīng shì Zhōngguó de shǒudū.","vi":"Bắc Kinh là thủ đô của Trung Quốc."}]'),
('吃','吃','chī','Ăn','To eat',1,'[{"cn":"我每天早上吃包子。","py":"Wǒ měitiān zǎoshàng chī bāozi.","vi":"Tôi ăn bánh bao mỗi sáng."}]'),
('喝','喝','hē','Uống','To drink',1,'[{"cn":"我喜欢喝茶。","py":"Wǒ xǐhuān hē chá.","vi":"Tôi thích uống trà."}]'),
('看','看','kàn','Nhìn, xem','To look / watch',1,'[{"cn":"我们去看电影吧。","py":"Wǒmen qù kàn diànyǐng ba.","vi":"Chúng ta đi xem phim nhé."}]'),
('听','聽','tīng','Nghe','To listen',1,'[{"cn":"我喜欢听音乐。","py":"Wǒ xǐhuān tīng yīnyuè.","vi":"Tôi thích nghe nhạc."}]'),
('说','說','shuō','Nói','To speak',1,'[{"cn":"请慢点说。","py":"Qǐng màn diǎn shuō.","vi":"Xin hãy nói chậm thôi."}]'),
('来','來','lái','Đến, lại','To come',1,'[{"cn":"请进来坐。","py":"Qǐng jìnlái zuò.","vi":"Mời vào ngồi."}]'),
('去','去','qù','Đi','To go',1,'[{"cn":"我们明天去公园。","py":"Wǒmen míngtiān qù gōngyuán.","vi":"Ngày mai chúng ta đi công viên."}]'),
('上','上','shàng','Lên, trên','Up / On',1,'[{"cn":"请上车。","py":"Qǐng shàng chē.","vi":"Xin mời lên xe."}]'),
('下','下','xià','Xuống, dưới','Down / Under',1,'[{"cn":"雨下得很大。","py":"Yǔ xià dé hěn dà.","vi":"Mưa to lắm."}]'),
('今天','今天','jīn tiān','Hôm nay','Today',1,'[{"cn":"今天是我的生日。","py":"Jīntiān shì wǒ de shēngrì.","vi":"Hôm nay là sinh nhật của tôi."}]'),
('明天','明天','míng tiān','Ngày mai','Tomorrow',1,'[{"cn":"明天我会打电话给你。","py":"Míngtiān wǒ huì dǎ diànhuà gěi nǐ.","vi":"Ngày mai tôi sẽ gọi điện cho bạn."}]'),
('昨天','昨天','zuó tiān','Hôm qua','Yesterday',1,'[{"cn":"昨天我去了图书馆。","py":"Zuótiān wǒ qùle túshūguǎn.","vi":"Hôm qua tôi đã đến thư viện."}]'),
('年','年','nián','Năm','Year',1,'[{"cn":"今年是二〇二六年。","py":"Jīnnián shì èr líng èr liù nián.","vi":"Năm nay là năm 2026."}]'),
('月','月','yuè','Tháng, Mặt trăng','Month / Moon',1,'[{"cn":"我喜欢五月的天气。","py":"Wǒ xǐhuān wǔyuè de tiānqì.","vi":"Tôi thích thời tiết tháng năm."}]'),
('日','日','rì','Ngày','Day / Sun',1,'[{"cn":"八月九日是我的生日。","py":"Bā yuè jiǔ rì shì wǒ de shēngrì.","vi":"Ngày 9/8 là sinh nhật của tôi."}]'),
('一','一','yī','Một','One',1,'[{"cn":"我想要一杯茶。","py":"Wǒ xiǎng yào yī bēi chá.","vi":"Tôi muốn một tách trà."}]'),
('二','二','èr','Hai','Two',1,'[{"cn":"我买了二斤苹果。","py":"Wǒ mǎile èr jīn píngguǒ.","vi":"Tôi mua hai cân táo."}]'),
('三','三','sān','Ba','Three',1,'[{"cn":"我家有三个人。","py":"Wǒjiā yǒu sān gè rén.","vi":"Nhà tôi có ba người."}]'),
('四','四','sì','Bốn','Four',1,'[{"cn":"他有四个孩子。","py":"Tā yǒu sì gè háizi.","vi":"Anh ấy có bốn đứa con."}]'),
('五','五','wǔ','Năm (số)','Five',1,'[{"cn":"我每天学习五个小时。","py":"Wǒ měitiān xuéxí wǔ gè xiǎoshí.","vi":"Tôi học tập năm tiếng mỗi ngày."}]'),
('六','六','liù','Sáu','Six',1,'[{"cn":"我有六本书。","py":"Wǒ yǒu liù běn shū.","vi":"Tôi có sáu quyển sách."}]'),
('七','七','qī','Bảy','Seven',1,'[{"cn":"他跑了七圈。","py":"Tā pǎole qī quān.","vi":"Anh ấy chạy bảy vòng."}]'),
('八','八','bā','Tám','Eight',1,'[{"cn":"八月非常热。","py":"Bā yuè fēicháng rè.","vi":"Tháng tám rất nóng."}]'),
('九','九','jiǔ','Chín','Nine',1,'[{"cn":"九月开学。","py":"Jiǔ yuè kāixué.","vi":"Tháng chín khai trường."}]'),
('十','十','shí','Mười','Ten',1,'[{"cn":"我等了十分钟。","py":"Wǒ děngle shí fēnzhōng.","vi":"Tôi chờ mười phút rồi."}]'),
('水','水','shuǐ','Nước','Water',1,'[{"cn":"每天要多喝水。","py":"Měitiān yào duō hē shuǐ.","vi":"Hàng ngày cần uống nhiều nước."}]'),
('茶','茶','chá','Trà','Tea',1,'[{"cn":"中国茶很有名。","py":"Zhōngguó chá hěn yǒumíng.","vi":"Trà Trung Quốc rất nổi tiếng."}]'),
('饭','飯','fàn','Cơm, bữa ăn','Rice / Meal',1,'[{"cn":"我们一起吃晚饭吧。","py":"Wǒmen yīqǐ chī wǎnfàn ba.","vi":"Chúng ta cùng ăn tối nhé."}]'),
('面条','麵條','miàn tiáo','Mì sợi','Noodles',1,'[{"cn":"我午饭吃了一碗面条。","py":"Wǒ wǔfàn chīle yī wǎn miàntiáo.","vi":"Bữa trưa tôi ăn một bát mì."}]'),
('苹果','蘋果','píng guǒ','Quả táo','Apple',1,'[{"cn":"吃苹果对身体好。","py":"Chī píngguǒ duì shēntǐ hǎo.","vi":"Ăn táo tốt cho sức khoẻ."}]'),
('猫','貓','māo','Con mèo','Cat',1,'[{"cn":"我家有一只猫。","py":"Wǒjiā yǒu yī zhī māo.","vi":"Nhà tôi có một con mèo."}]'),
('狗','狗','gǒu','Con chó','Dog',1,'[{"cn":"他们家有一只大狗。","py":"Tāmen jiā yǒu yī zhī dà gǒu.","vi":"Nhà họ có một con chó lớn."}]'),
('书','書','shū','Sách','Book',1,'[{"cn":"我每天晚上读一小时的书。","py":"Wǒ měitiān wǎnshàng dú yī xiǎoshí de shū.","vi":"Tôi đọc sách một tiếng vào mỗi tối."}]'),
('电视','電視','diàn shì','Tivi','Television',1,'[{"cn":"他们正在看电视。","py":"Tāmen zhèngzài kàn diànshì.","vi":"Họ đang xem tivi."}]'),
('电脑','電腦','diàn nǎo','Máy tính','Computer',1,'[{"cn":"我用电脑工作。","py":"Wǒ yòng diànnǎo gōngzuò.","vi":"Tôi dùng máy tính để làm việc."}]'),
('手机','手機','shǒu jī','Điện thoại di động','Mobile phone',1,'[{"cn":"我忘记带手机了。","py":"Wǒ wàngjì dài shǒujī le.","vi":"Tôi quên mang điện thoại rồi."}]'),
('飞机','飛機','fēi jī','Máy bay','Airplane',1,'[{"cn":"我们坐飞机去上海。","py":"Wǒmen zuò fēijī qù Shànghǎi.","vi":"Chúng tôi đi máy bay tới Thượng Hải."}]'),
('出租车','出租車','chū zū chē','Xe taxi','Taxi',1,'[{"cn":"我叫了一辆出租车。","py":"Wǒ jiàole yī liàng chūzūchē.","vi":"Tôi gọi một chiếc taxi."}]'),
('钱','錢','qián','Tiền','Money',1,'[{"cn":"这件衣服要多少钱？","py":"Zhè jiàn yīfú yào duōshǎo qián?","vi":"Bộ quần áo này bao nhiêu tiền?"}]'),

-- ========== HSK 2 ==========
('高兴','高興','gāo xìng','Vui mừng','Happy',2,'[{"cn":"见到你我很高兴。","py":"Jiàndào nǐ wǒ hěn gāoxìng.","vi":"Tôi rất vui khi gặp bạn."},{"cn":"她今天看起来不高兴。","py":"Tā jīntiān kàn qǐlái bù gāoxìng.","vi":"Hôm nay trông cô ấy có vẻ không vui."}]'),
('学习','學習','xué xí','Học tập','To study',2,'[{"cn":"你每天学习几个小时？","py":"Nǐ měitiān xuéxí jǐ gè xiǎoshí?","vi":"Mỗi ngày bạn học bao nhiêu tiếng?"},{"cn":"学习中文需要耐心。","py":"Xuéxí Zhōngwén xūyào nàixīn.","vi":"Học tiếng Trung cần sự kiên nhẫn."}]'),
('工作','工作','gōng zuò','Làm việc, công việc','Work / Job',2,'[{"cn":"我在一家公司工作。","py":"Wǒ zài yījiā gōngsī gōngzuò.","vi":"Tôi làm việc tại một công ty."},{"cn":"你是做什么工作的？","py":"Nǐ shì zuò shénme gōngzuò de?","vi":"Bạn làm nghề gì?"}]'),
('身体','身體','shēn tǐ','Sức khoẻ, thân thể','Body / Health',2,'[{"cn":"你要注意身体。","py":"Nǐ yào zhùyì shēntǐ.","vi":"Bạn cần chú ý giữ gìn sức khoẻ."},{"cn":"运动对身体很好。","py":"Yùndòng duì shēntǐ hěn hǎo.","vi":"Tập thể dục rất tốt cho sức khoẻ."}]'),
('时候','時候','shí hòu','Lúc, khi','Time (when)',2,'[{"cn":"吃饭的时候不要玩手机。","py":"Chīfàn de shíhòu bùyào wán shǒujī.","vi":"Đừng chơi điện thoại khi ăn cơm."},{"cn":"你什么时候有空？","py":"Nǐ shénme shíhòu yǒu kòng?","vi":"Bạn rảnh vào lúc nào?"}]'),
('地方','地方','dì fāng','Địa điểm, nơi chốn','Place',2,'[{"cn":"这个地方很美。","py":"Zhège dìfāng hěn měi.","vi":"Nơi này rất đẹp."},{"cn":"你去过哪些地方？","py":"Nǐ qùguò nǎxiē dìfāng?","vi":"Bạn đã đến những nơi nào?"}]'),
('问题','問題','wèn tí','Vấn đề, câu hỏi','Problem / Question',2,'[{"cn":"这个问题很难。","py":"Zhège wèntí hěn nán.","vi":"Câu hỏi này rất khó."},{"cn":"有什么问题可以问我。","py":"Yǒu shénme wèntí kěyǐ wèn wǒ.","vi":"Có câu hỏi gì thì có thể hỏi tôi."}]'),
('知道','知道','zhī dào','Biết','To know',2,'[{"cn":"我不知道他住在哪里。","py":"Wǒ bù zhīdào tā zhù zài nǎlǐ.","vi":"Tôi không biết anh ấy ở đâu."},{"cn":"你知道这个字怎么读吗？","py":"Nǐ zhīdào zhège zì zěnme dú ma?","vi":"Bạn có biết chữ này đọc thế nào không?"}]'),
('觉得','覺得','jué de','Cảm thấy, cho rằng','To feel / think',2,'[{"cn":"我觉得这道菜很好吃。","py":"Wǒ juéde zhè dào cài hěn hǎochī.","vi":"Tôi thấy món này ngon lắm."},{"cn":"你觉得怎么样？","py":"Nǐ juéde zěnme yàng?","vi":"Bạn thấy thế nào?"}]'),
('喜欢','喜歡','xǐ huān','Thích','To like',2,'[{"cn":"我很喜欢中国文化。","py":"Wǒ hěn xǐhuān Zhōngguó wénhuà.","vi":"Tôi rất thích văn hoá Trung Quốc."},{"cn":"你喜欢什么运动？","py":"Nǐ xǐhuān shénme yùndòng?","vi":"Bạn thích môn thể thao gì?"}]'),
('认为','認為','rèn wéi','Cho rằng, cho là','To think / believe',2,'[{"cn":"我认为这个方法不对。","py":"Wǒ rènwéi zhège fāngfǎ bù duì.","vi":"Tôi cho rằng phương pháp này không đúng."}]'),
('可以','可以','kě yǐ','Có thể, được phép','Can / May',2,'[{"cn":"我可以帮你吗？","py":"Wǒ kěyǐ bāng nǐ ma?","vi":"Tôi có thể giúp bạn không?"},{"cn":"你可以随时来找我。","py":"Nǐ kěyǐ suíshí lái zhǎo wǒ.","vi":"Bạn có thể đến gặp tôi bất cứ lúc nào."}]'),
('因为','因為','yīn wèi','Vì, bởi vì','Because',2,'[{"cn":"因为下雨，我没去。","py":"Yīnwèi xià yǔ, wǒ méi qù.","vi":"Vì trời mưa nên tôi không đi."}]'),
('所以','所以','suǒ yǐ','Cho nên, vì vậy','Therefore',2,'[{"cn":"他努力学习，所以考得很好。","py":"Tā nǔlì xuéxí, suǒyǐ kǎo dé hěn hǎo.","vi":"Anh ấy học chăm chỉ nên thi tốt."}]'),
('但是','但是','dàn shì','Nhưng','But / However',2,'[{"cn":"我想去，但是没有时间。","py":"Wǒ xiǎng qù, dànshì méiyǒu shíjiān.","vi":"Tôi muốn đi nhưng không có thời gian."}]'),
('如果','如果','rú guǒ','Nếu','If',2,'[{"cn":"如果明天不下雨，我们就去。","py":"Rúguǒ míngtiān bù xià yǔ, wǒmen jiù qù.","vi":"Nếu ngày mai không mưa thì chúng ta sẽ đi."}]'),
('一起','一起','yī qǐ','Cùng nhau','Together',2,'[{"cn":"我们一起去看电影吧。","py":"Wǒmen yīqǐ qù kàn diànyǐng ba.","vi":"Chúng ta cùng đi xem phim nhé."}]'),
('非常','非常','fēi cháng','Rất, vô cùng','Extremely',2,'[{"cn":"我非常感谢你的帮助。","py":"Wǒ fēicháng gǎnxiè nǐ de bāngzhù.","vi":"Tôi vô cùng biết ơn sự giúp đỡ của bạn."}]'),
('已经','已經','yǐ jīng','Đã, rồi','Already',2,'[{"cn":"我已经吃过了。","py":"Wǒ yǐjīng chīguò le.","vi":"Tôi đã ăn rồi."}]'),
('还是','還是','hái shì','Hay là (hỏi), vẫn là','Or / Still',2,'[{"cn":"你喝茶还是咖啡？","py":"Nǐ hē chá háishi kāfēi?","vi":"Bạn uống trà hay cà phê?"}]'),
('比较','比較','bǐ jiào','Tương đối, so sánh','Comparatively',2,'[{"cn":"这家餐厅比较贵。","py":"Zhè jiā cāntīng bǐjiào guì.","vi":"Nhà hàng này tương đối đắt."}]'),
('同时','同時','tóng shí','Đồng thời, cùng lúc','At the same time',2,'[{"cn":"他同时学习两门语言。","py":"Tā tóngshí xuéxí liǎng mén yǔyán.","vi":"Anh ấy cùng lúc học hai ngôn ngữ."}]'),
('帮助','幫助','bāng zhù','Giúp đỡ','To help',2,'[{"cn":"谢谢你帮助我。","py":"Xièxiè nǐ bāngzhù wǒ.","vi":"Cảm ơn bạn đã giúp tôi."}]'),
('告诉','告訴','gào sù','Nói cho biết, thông báo','To tell',2,'[{"cn":"请告诉我怎么去火车站。","py":"Qǐng gàosù wǒ zěnme qù huǒchēzhàn.","vi":"Xin hãy chỉ cho tôi đường đến ga tàu."}]'),
('希望','希望','xī wàng','Hy vọng, mong muốn','Hope / Wish',2,'[{"cn":"我希望你能来参加。","py":"Wǒ xīwàng nǐ néng lái cānjiā.","vi":"Tôi mong bạn có thể đến tham dự."}]'),
('准备','準備','zhǔn bèi','Chuẩn bị','To prepare',2,'[{"cn":"我在准备明天的考试。","py":"Wǒ zài zhǔnbèi míngtiān de kǎoshì.","vi":"Tôi đang chuẩn bị cho kỳ thi ngày mai."}]'),
('开始','開始','kāi shǐ','Bắt đầu','To start',2,'[{"cn":"电影八点开始。","py":"Diànyǐng bā diǎn kāishǐ.","vi":"Phim bắt đầu lúc tám giờ."}]'),
('结束','結束','jié shù','Kết thúc','To end',2,'[{"cn":"会议几点结束？","py":"Huìyì jǐ diǎn jiéshù?","vi":"Cuộc họp kết thúc lúc mấy giờ?"}]'),
('需要','需要','xū yào','Cần, cần thiết','To need',2,'[{"cn":"你需要帮忙吗？","py":"Nǐ xūyào bāngmáng ma?","vi":"Bạn có cần giúp đỡ không?"}]'),
('认识','認識','rèn shi','Quen biết, nhận ra','To know / recognize',2,'[{"cn":"很高兴认识你。","py":"Hěn gāoxìng rènshi nǐ.","vi":"Rất vui được quen biết bạn."}]'),
('等','等','děng','Chờ, đợi','To wait',2,'[{"cn":"我在等公共汽车。","py":"Wǒ zài děng gōnggòng qìchē.","vi":"Tôi đang chờ xe buýt."}]'),
('想','想','xiǎng','Muốn, nghĩ','To want / think',2,'[{"cn":"我想去中国旅游。","py":"Wǒ xiǎng qù Zhōngguó lǚyóu.","vi":"Tôi muốn đi du lịch Trung Quốc."}]'),
('可能','可能','kě néng','Có thể, có khả năng','Possible / Maybe',2,'[{"cn":"他可能今天不来了。","py":"Tā kěnéng jīntiān bù lái le.","vi":"Có thể anh ấy hôm nay không đến."}]'),
('当然','當然','dāng rán','Đương nhiên, tất nhiên','Of course',2,'[{"cn":"当然可以，请坐吧。","py":"Dāngrán kěyǐ, qǐng zuò ba.","vi":"Tất nhiên được, xin mời ngồi."}]'),
('关系','關係','guān xi','Quan hệ, liên quan','Relationship',2,'[{"cn":"我们关系很好。","py":"Wǒmen guānxi hěn hǎo.","vi":"Chúng tôi có mối quan hệ rất tốt."}]'),
('游戏','遊戲','yóu xì','Trò chơi, game','Game',2,'[{"cn":"他非常喜欢玩游戏。","py":"Tā fēicháng xǐhuān wán yóuxì.","vi":"Anh ấy rất thích chơi game."},{"cn":"游戏可以帮助孩子学习。","py":"Yóuxì kěyǐ bāngzhù háizi xuéxí.","vi":"Trò chơi có thể giúp trẻ em học tập."}]'),
('汉语','漢語','hàn yǔ','Tiếng Hán, tiếng Trung','Chinese language',2,'[{"cn":"我在学习汉语。","py":"Wǒ zài xuéxí Hànyǔ.","vi":"Tôi đang học tiếng Trung."},{"cn":"汉语是世界上使用人数最多的语言。","py":"Hànyǔ shì shìjiè shàng shǐyòng rénshù zuì duō de yǔyán.","vi":"Tiếng Trung là ngôn ngữ có nhiều người sử dụng nhất thế giới."}]'),
('普通话','普通話','pǔ tōng huà','Tiếng phổ thông','Mandarin',2,'[{"cn":"学普通话对我来说很重要。","py":"Xué Pǔtōnghuà duì wǒ lái shuō hěn zhòngyào.","vi":"Việc học tiếng phổ thông rất quan trọng với tôi."}]'),
('意思','意思','yì si','Ý nghĩa, ý tứ','Meaning',2,'[{"cn":"这个词是什么意思？","py":"Zhège cí shì shénme yìsi?","vi":"Từ này có nghĩa là gì?"}]'),
('方便','方便','fāng biàn','Tiện lợi, thuận tiện','Convenient',2,'[{"cn":"住在这里很方便。","py":"Zhù zài zhèlǐ hěn fāngbiàn.","vi":"Sống ở đây rất tiện lợi."}]'),
('小时','小時','xiǎo shí','Giờ (đơn vị thời gian)','Hour',2,'[{"cn":"我每天工作八个小时。","py":"Wǒ měitiān gōngzuò bā gè xiǎoshí.","vi":"Mỗi ngày tôi làm việc tám tiếng."}]'),
('分钟','分鐘','fēn zhōng','Phút','Minute',2,'[{"cn":"我只需要五分钟。","py":"Wǒ zhǐ xūyào wǔ fēnzhōng.","vi":"Tôi chỉ cần năm phút thôi."}]'),
('医院','醫院','yī yuàn','Bệnh viện','Hospital',2,'[{"cn":"我要去医院看病。","py":"Wǒ yào qù yīyuàn kànbìng.","vi":"Tôi phải đến bệnh viện khám."}]'),
('药','藥','yào','Thuốc','Medicine',2,'[{"cn":"你每天要按时吃药。","py":"Nǐ měitiān yào ànshí chī yào.","vi":"Bạn phải uống thuốc đúng giờ mỗi ngày."}]'),
('超市','超市','chāo shì','Siêu thị','Supermarket',2,'[{"cn":"我去超市买东西。","py":"Wǒ qù chāoshì mǎi dōngxi.","vi":"Tôi đến siêu thị mua đồ."}]'),
('公司','公司','gōng sī','Công ty','Company',2,'[{"cn":"我在一家大公司上班。","py":"Wǒ zài yījiā dà gōngsī shàngbān.","vi":"Tôi làm ở một công ty lớn."}]'),

-- ========== HSK 3 ==========
('成功','成功','chéng gōng','Thành công','Success',3,'[{"cn":"他终于成功了。","py":"Tā zhōngyú chénggōng le.","vi":"Cuối cùng anh ấy đã thành công."},{"cn":"成功需要努力和坚持。","py":"Chénggōng xūyào nǔlì hé jiānchí.","vi":"Thành công cần sự nỗ lực và kiên trì."}]'),
('努力','努力','nǔ lì','Nỗ lực, cố gắng','To work hard',3,'[{"cn":"他很努力，成绩很好。","py":"Tā hěn nǔlì, chéngjì hěn hǎo.","vi":"Anh ấy rất cố gắng nên thành tích rất tốt."}]'),
('经验','經驗','jīng yàn','Kinh nghiệm','Experience',3,'[{"cn":"他有丰富的工作经验。","py":"Tā yǒu fēngfù de gōngzuò jīngyàn.","vi":"Anh ấy có kinh nghiệm làm việc phong phú."}]'),
('文化','文化','wén huà','Văn hóa','Culture',3,'[{"cn":"中国文化历史悠久。","py":"Zhōngguó wénhuà lìshǐ yōujiǔ.","vi":"Văn hóa Trung Quốc có lịch sử lâu đời."}]'),
('社会','社會','shè huì','Xã hội','Society',3,'[{"cn":"读大学对进入社会有很大帮助。","py":"Dú dàxué duì jìnrù shèhuì yǒu hěn dà bāngzhù.","vi":"Học đại học rất có ích cho việc bước vào xã hội."}]'),
('发展','發展','fā zhǎn','Phát triển','Development',3,'[{"cn":"中国经济发展非常快。","py":"Zhōngguó jīngjì fāzhǎn fēicháng kuài.","vi":"Kinh tế Trung Quốc phát triển rất nhanh."}]'),
('环境','環境','huán jìng','Môi trường, hoàn cảnh','Environment',3,'[{"cn":"保护环境是每个人的责任。","py":"Bǎohù huánjìng shì měi gè rén de zérèn.","vi":"Bảo vệ môi trường là trách nhiệm của mỗi người."}]'),
('教育','教育','jiào yù','Giáo dục','Education',3,'[{"cn":"父母非常重视孩子的教育。","py":"Fùmǔ fēicháng zhòngshì háizi de jiàoyù.","vi":"Cha mẹ rất coi trọng việc giáo dục con cái."}]'),
('健康','健康','jiàn kāng','Sức khoẻ; khoẻ mạnh','Health / Healthy',3,'[{"cn":"健康比什么都重要。","py":"Jiànkāng bǐ shénme dōu zhòngyào.","vi":"Sức khoẻ quan trọng hơn bất cứ điều gì."},{"cn":"保持健康的生活方式很重要。","py":"Bǎochí jiànkāng de shēnghuó fāngshì hěn zhòngyào.","vi":"Duy trì lối sống lành mạnh rất quan trọng."}]'),
('科技','科技','kē jì','Khoa học công nghệ','Science and technology',3,'[{"cn":"科技改变了我们的生活。","py":"Kējì gǎibiànle wǒmen de shēnghuó.","vi":"Khoa học công nghệ đã thay đổi cuộc sống của chúng ta."}]'),
('互联网','互聯網','hù lián wǎng','Internet','Internet',3,'[{"cn":"互联网让世界变得更小。","py":"Hùliánwǎng ràng shìjiè biàn dé gèng xiǎo.","vi":"Internet làm cho thế giới trở nên nhỏ hơn."}]'),
-- duplicate: 手机
('旅游','旅遊','lǚ yóu','Du lịch','Tourism / Travel',3,'[{"cn":"暑假我们去欧洲旅游。","py":"Shǔjià wǒmen qù Ōuzhōu lǚyóu.","vi":"Kỳ nghỉ hè chúng tôi đi du lịch châu Âu."}]'),
('机会','機會','jī huì','Cơ hội','Opportunity',3,'[{"cn":"要抓住每一个机会。","py":"Yào zhuāzhù měi yīgè jīhuì.","vi":"Phải nắm bắt từng cơ hội."}]'),
('计划','計劃','jì huà','Kế hoạch','Plan',3,'[{"cn":"你有什么假期计划？","py":"Nǐ yǒu shénme jiàqī jìhuà?","vi":"Bạn có kế hoạch nghỉ lễ gì không?"}]'),
('决定','決定','jué dìng','Quyết định','Decision / To decide',3,'[{"cn":"我决定去中国留学。","py":"Wǒ juédìng qù Zhōngguó liúxué.","vi":"Tôi quyết định đi du học ở Trung Quốc."}]'),
('影响','影響','yǐng xiǎng','Ảnh hưởng','Influence',3,'[{"cn":"天气影响了我们的心情。","py":"Tiānqì yǐngxiǎngle wǒmen de xīnqíng.","vi":"Thời tiết ảnh hưởng đến tâm trạng của chúng ta."}]'),
('表达','表達','biǎo dá','Biểu đạt, thể hiện','To express',3,'[{"cn":"他很善于表达自己的想法。","py":"Tā hěn shànyú biǎodá zìjǐ de xiǎngfǎ.","vi":"Anh ấy rất giỏi thể hiện suy nghĩ của mình."}]'),
('理解','理解','lǐ jiě','Hiểu, lý giải','To understand',3,'[{"cn":"我不太理解这道题。","py":"Wǒ bù tài lǐjiě zhè dào tí.","vi":"Tôi không hiểu lắm bài toán này."}]'),
('联系','聯繫','lián xì','Liên lạc, liên hệ','To contact',3,'[{"cn":"请保持联系。","py":"Qǐng bǎochí liánxì.","vi":"Hãy giữ liên lạc nhé."}]'),
('提高','提高','tí gāo','Nâng cao, cải thiện','To improve',3,'[{"cn":"我想提高我的汉语水平。","py":"Wǒ xiǎng tígāo wǒ de Hànyǔ shuǐpíng.","vi":"Tôi muốn nâng cao trình độ tiếng Trung của mình."}]'),
('参加','參加','cān jiā','Tham gia','To participate',3,'[{"cn":"你愿意参加这个活动吗？","py":"Nǐ yuànyì cānjiā zhège huódòng ma?","vi":"Bạn có muốn tham gia hoạt động này không?"}]'),
('考试','考試','kǎo shì','Kỳ thi, kiểm tra','Exam / Test',3,'[{"cn":"下周我有一次重要的考试。","py":"Xià zhōu wǒ yǒu yīcì zhòngyào de kǎoshì.","vi":"Tuần tới tôi có một kỳ thi quan trọng."}]'),
('结果','結果','jié guǒ','Kết quả','Result',3,'[{"cn":"考试结果什么时候公布？","py":"Kǎoshì jiéguǒ shénme shíhòu gōngbù?","vi":"Khi nào công bố kết quả thi?"}]'),
('方法','方法','fāng fǎ','Phương pháp, cách thức','Method',3,'[{"cn":"你有什么好的学习方法？","py":"Nǐ yǒu shénme hǎo de xuéxí fāngfǎ?","vi":"Bạn có phương pháp học tập tốt nào không?"}]'),
-- duplicate: 问题
('感觉','感覺','gǎn jué','Cảm giác, cảm thấy','Feeling',3,'[{"cn":"我有一种奇怪的感觉。","py":"Wǒ yǒu yī zhǒng qíguài de gǎnjué.","vi":"Tôi có một cảm giác kỳ lạ."}]'),
('情况','情況','qíng kuàng','Tình huống, tình hình','Situation',3,'[{"cn":"你的情况怎么样？","py":"Nǐ de qíngkuàng zěnme yàng?","vi":"Tình hình của bạn thế nào?"}]'),
('注意','注意','zhù yì','Chú ý, để ý','To pay attention',3,'[{"cn":"过马路要注意安全。","py":"Guò mǎlù yào zhùyì ānquán.","vi":"Khi qua đường phải chú ý an toàn."}]'),
('继续','繼續','jì xù','Tiếp tục','To continue',3,'[{"cn":"请继续说。","py":"Qǐng jìxù shuō.","vi":"Xin hãy tiếp tục nói."}]'),
('改变','改變','gǎi biàn','Thay đổi, biến đổi','To change',3,'[{"cn":"人是可以改变的。","py":"Rén shì kěyǐ gǎibiàn de.","vi":"Con người có thể thay đổi được."}]'),
-- duplicate: 已经
('突然','突然','tū rán','Đột nhiên, bỗng nhiên','Suddenly',3,'[{"cn":"天气突然变冷了。","py":"Tiānqì tūrán biàn lěng le.","vi":"Thời tiết đột nhiên trở lạnh."}]'),
('尤其','尤其','yóu qí','Đặc biệt là, nhất là','Especially',3,'[{"cn":"我喜欢运动，尤其是游泳。","py":"Wǒ xǐhuān yùndòng, yóuqí shì yóuyǒng.","vi":"Tôi thích thể thao, đặc biệt là bơi lội."}]'),
('经济','經濟','jīng jì','Kinh tế','Economy',3,'[{"cn":"中国经济增长很快。","py":"Zhōngguó jīngjì zēngzhǎng hěn kuài.","vi":"Kinh tế Trung Quốc tăng trưởng rất nhanh."}]'),
('政治','政治','zhèng zhì','Chính trị','Politics',3,'[{"cn":"他对政治不感兴趣。","py":"Tā duì zhèngzhì bù gǎn xìngqù.","vi":"Anh ấy không hứng thú với chính trị."}]'),
('语言','語言','yǔ yán','Ngôn ngữ','Language',3,'[{"cn":"学习多种语言很有用。","py":"Xuéxí duō zhǒng yǔyán hěn yǒuyòng.","vi":"Học nhiều ngôn ngữ rất có ích."}]'),
('历史','歷史','lì shǐ','Lịch sử','History',3,'[{"cn":"中国有五千年的历史。","py":"Zhōngguó yǒu wǔqiān nián de lìshǐ.","vi":"Trung Quốc có lịch sử năm nghìn năm."}]'),
('音乐','音樂','yīn yuè','Âm nhạc','Music',3,'[{"cn":"音乐能够改善心情。","py":"Yīnyuè nénggòu gǎishàn xīnqíng.","vi":"Âm nhạc có thể cải thiện tâm trạng."}]'),
('运动','運動','yùn dòng','Vận động, thể thao','Sport / Exercise',3,'[{"cn":"坚持运动对健康有好处。","py":"Jiānchí yùndòng duì jiànkāng yǒu hǎochu.","vi":"Kiên trì tập thể dục rất có lợi cho sức khoẻ."},{"cn":"你喜欢什么运动？","py":"Nǐ xǐhuān shénme yùndòng?","vi":"Bạn thích môn thể thao gì?"}]'),
('爱好','愛好','ài hào','Sở thích','Hobby',3,'[{"cn":"我的爱好是读书和旅游。","py":"Wǒ de àihào shì dúshū hé lǚyóu.","vi":"Sở thích của tôi là đọc sách và du lịch."}]'),
('比赛','比賽','bǐ sài','Thi đấu, cuộc thi','Competition',3,'[{"cn":"明天有一场足球比赛。","py":"Míngtiān yǒu yī chǎng zúqiú bǐsài.","vi":"Ngày mai có một trận đấu bóng đá."}]'),
('聪明','聰明','cōng míng','Thông minh, thao lược','Clever / Smart',3,'[{"cn":"这个孩子非常聪明。","py":"Zhège háizi fēicháng cōngming.","vi":"Đứa trẻ này cực kỳ thông minh."},{"cn":"聪明不一定等于努力。","py":"Cōngming bù yīdìng děngyú nǔlì.","vi":"Thông minh không nhất thiết đồng nghĩa với chăm chỉ."}]'),
('勤奋','勤奮','qín fèn','Siêng năng, chăm chỉ','Diligent',3,'[{"cn":"她是一个勤奋的学生。","py":"Tā shì yīgè qínfèn de xuéshēng.","vi":"Cô ấy là một học sinh chăm chỉ."}]'),
('耐心','耐心','nài xīn','Kiên nhẫn, nhẫn nại','Patient',3,'[{"cn":"学好一门语言需要耐心。","py":"Xué hǎo yī mén yǔyán xūyào nàixīn.","vi":"Học giỏi một ngôn ngữ cần sự kiên nhẫn."}]'),

-- ========== Từ thông dụng hàng ngày ==========
('好吃','好吃','hǎo chī','Ngon (thức ăn)','Delicious',2,'[{"cn":"这家餐厅的菜很好吃。","py":"Zhè jiā cāntīng de cài hěn hǎochī.","vi":"Món ăn ở nhà hàng này rất ngon."},{"cn":"妈妈做的饺子特别好吃。","py":"Māma zuò de jiǎozi tèbié hǎochī.","vi":"Bánh sủi cảo mẹ làm đặc biệt ngon."}]'),
('漂亮','漂亮','piào liang','Đẹp (ngoại hình)','Beautiful / Pretty',2,'[{"cn":"你今天穿得很漂亮。","py":"Nǐ jīntiān chuān dé hěn piàoliang.","vi":"Hôm nay bạn mặc rất đẹp."},{"cn":"这朵花真漂亮！","py":"Zhè duǒ huā zhēn piàoliang!","vi":"Bông hoa này thật đẹp!"}]'),
('天气','天氣','tiān qì','Thời tiết','Weather',2,'[{"cn":"今天天气怎么样？","py":"Jīntiān tiānqì zěnmeyàng?","vi":"Hôm nay thời tiết thế nào?"},{"cn":"明天天气预报说有雨。","py":"Míngtiān tiānqì yùbào shuō yǒu yǔ.","vi":"Dự báo thời tiết nói ngày mai có mưa."}]'),
('咖啡','咖啡','kā fēi','Cà phê','Coffee',2,'[{"cn":"我每天早上喝一杯咖啡。","py":"Wǒ měitiān zǎoshàng hē yī bēi kāfēi.","vi":"Mỗi sáng tôi uống một tách cà phê."},{"cn":"你喝咖啡还是茶？","py":"Nǐ hē kāfēi háishi chá?","vi":"Bạn uống cà phê hay trà?"}]'),
('快乐','快樂','kuài lè','Vui vẻ, hạnh phúc','Happy / Joyful',2,'[{"cn":"祝你生日快乐！","py":"Zhù nǐ shēngrì kuàilè!","vi":"Chúc mừng sinh nhật bạn!"},{"cn":"我希望你永远快乐。","py":"Wǒ xīwàng nǐ yǒngyuǎn kuàilè.","vi":"Tôi mong bạn mãi mãi vui vẻ hạnh phúc."}]'),
('美丽','美麗','měi lì','Đẹp đẽ, xinh đẹp','Beautiful',3,'[{"cn":"这座城市非常美丽。","py":"Zhè zuò chéngshì fēicháng měilì.","vi":"Thành phố này rất đẹp."},{"cn":"她是一位美丽的姑娘。","py":"Tā shì yī wèi měilì de gūniang.","vi":"Cô ấy là một cô gái xinh đẹp."}]'),
('开心','開心','kāi xīn','Vui, phấn khởi','Happy',2,'[{"cn":"看到你我很开心。","py":"Kàndào nǐ wǒ hěn kāixīn.","vi":"Gặp bạn tôi rất vui."},{"cn":"今天是开心的一天。","py":"Jīntiān shì kāixīn de yī tiān.","vi":"Hôm nay là một ngày vui."}]'),
('难过','難過','nán guò','Buồn, đau lòng','Sad',2,'[{"cn":"听到这个消息，我很难过。","py":"Tīngdào zhège xiāoxi, wǒ hěn nánguò.","vi":"Nghe tin đó tôi rất buồn."},{"cn":"别难过，一切都会好起来的。","py":"Bié nánguò, yīqiè dōu huì hǎo qǐlái de.","vi":"Đừng buồn, mọi chuyện rồi sẽ ổn thôi."}]'),
('生气','生氣','shēng qì','Tức giận','Angry',2,'[{"cn":"他因为迟到而生气。","py":"Tā yīnwèi chídào ér shēngqì.","vi":"Anh ấy tức giận vì đến muộn."},{"cn":"别生气，这只是个误会。","py":"Bié shēngqì, zhè zhǐshì gè wùhuì.","vi":"Đừng tức giận, đây chỉ là hiểu lầm thôi."}]'),
('担心','擔心','dān xīn','Lo lắng, lo ngại','To worry',2,'[{"cn":"妈妈很担心我的身体。","py":"Māma hěn dānxīn wǒ de shēntǐ.","vi":"Mẹ rất lo lắng cho sức khoẻ của tôi."},{"cn":"不用担心，我会帮你的。","py":"Bùyòng dānxīn, wǒ huì bāng nǐ de.","vi":"Đừng lo lắng, tôi sẽ giúp bạn."}]'),
('紧张','緊張','jǐn zhāng','Căng thẳng, hồi hộp','Nervous / Tense',2,'[{"cn":"考试前我很紧张。","py":"Kǎoshì qián wǒ hěn jǐnzhāng.","vi":"Trước kỳ thi tôi rất hồi hộp."},{"cn":"深呼吸，不要紧张。","py":"Shēn hūxī, bùyào jǐnzhāng.","vi":"Hít thở sâu đi, đừng căng thẳng."}]'),
-- duplicate: 喜欢
('爱','愛','ài','Yêu, yêu thích','To love',1,'[{"cn":"我爱我的家人。","py":"Wǒ ài wǒ de jiārén.","vi":"Tôi yêu gia đình của tôi."},{"cn":"爱是最美好的情感。","py":"Ài shì zuì měihǎo de qínggǎn.","vi":"Tình yêu là cảm xúc đẹp đẽ nhất."}]'),
('睡觉','睡覺','shuì jiào','Ngủ','To sleep',1,'[{"cn":"你几点睡觉？","py":"Nǐ jǐ diǎn shuìjiào?","vi":"Bạn ngủ lúc mấy giờ?"},{"cn":"我昨晚睡得很好。","py":"Wǒ zuówǎn shuì de hěn hǎo.","vi":"Tối qua tôi ngủ rất ngon."}]'),
('起床','起床','qǐ chuáng','Dậy, ngủ dậy','To get up',1,'[{"cn":"我每天六点起床。","py":"Wǒ měitiān liù diǎn qǐchuáng.","vi":"Tôi thức dậy lúc sáu giờ mỗi ngày."},{"cn":"周末我喜欢晚一点起床。","py":"Zhōumò wǒ xǐhuān wǎn yīdiǎn qǐchuáng.","vi":"Cuối tuần tôi thích dậy muộn hơn."}]'),
('洗澡','洗澡','xǐ zǎo','Tắm rửa','To shower / bathe',1,'[{"cn":"我每天晚上洗澡。","py":"Wǒ měitiān wǎnshàng xǐzǎo.","vi":"Tôi tắm mỗi tối."}]'),
('锻炼','鍛煉','duàn liàn','Tập luyện, rèn luyện','To exercise / train',3,'[{"cn":"每天锻炼对身体有好处。","py":"Měitiān duànliàn duì shēntǐ yǒu hǎochu.","vi":"Tập luyện mỗi ngày rất có lợi cho sức khoẻ."},{"cn":"你平时怎么锻炼？","py":"Nǐ píngshí zěnme duànliàn?","vi":"Bình thường bạn tập luyện như thế nào?"}]'),
('跑步','跑步','pǎo bù','Chạy bộ','Running / Jogging',2,'[{"cn":"我每天早上跑步。","py":"Wǒ měitiān zǎoshàng pǎobù.","vi":"Tôi chạy bộ mỗi sáng."},{"cn":"跑步是最简单的运动。","py":"Pǎobù shì zuì jiǎndān de yùndòng.","vi":"Chạy bộ là môn thể thao đơn giản nhất."}]'),
('游泳','游泳','yóu yǒng','Bơi lội','Swimming',2,'[{"cn":"夏天我喜欢去游泳。","py":"Xiàtiān wǒ xǐhuān qù yóuyǒng.","vi":"Mùa hè tôi thích đi bơi."},{"cn":"你会游泳吗？","py":"Nǐ huì yóuyǒng ma?","vi":"Bạn có biết bơi không?"}]'),
('书包','書包','shū bāo','Cặp sách, túi xách','Backpack / School bag',1,'[{"cn":"我忘记带书包了。","py":"Wǒ wàngjì dài shūbāo le.","vi":"Tôi quên mang cặp sách rồi."}]'),
('作业','作業','zuò yè','Bài tập về nhà','Homework',1,'[{"cn":"今天的作业很多。","py":"Jīntiān de zuòyè hěn duō.","vi":"Bài tập hôm nay rất nhiều."},{"cn":"我要先做完作业再玩。","py":"Wǒ yào xiān zuò wán zuòyè zài wán.","vi":"Tôi phải làm xong bài tập rồi mới chơi."}]'),
-- duplicate: 考试
('成绩','成績','chéng jì','Thành tích, điểm số','Grade / Achievement',3,'[{"cn":"这次考试我成绩不好。","py":"Zhècì kǎoshì wǒ chéngjì bù hǎo.","vi":"Kỳ thi này thành tích của tôi không tốt."},{"cn":"他的成绩一直很优秀。","py":"Tā de chéngjì yīzhí hěn yōuxiù.","vi":"Thành tích của anh ấy luôn xuất sắc."}]'),
('餐厅','餐廳','cān tīng','Nhà hàng, phòng ăn','Restaurant',2,'[{"cn":"我们去那家新开的餐厅吃饭吧。","py":"Wǒmen qù nà jiā xīn kāi de cāntīng chīfàn ba.","vi":"Chúng ta đến nhà hàng mới mở đó ăn nhé."}]'),
('点菜','點菜','diǎn cài','Gọi món','To order food',2,'[{"cn":"请问您要点菜吗？","py":"Qǐngwèn nín yào diǎncài ma?","vi":"Xin hỏi quý khách muốn gọi món chưa?"}]'),
('买单','買單','mǎi dān','Tính tiền, trả tiền','To pay the bill',2,'[{"cn":"服务员，买单！","py":"Fúwùyuán, mǎidān!","vi":"Phục vụ ơi, tính tiền cho tôi!"}]'),
('地铁','地鐵','dì tiě','Tàu điện ngầm, metro','Subway / Metro',2,'[{"cn":"我每天坐地铁上班。","py":"Wǒ měitiān zuò dìtiě shàngbān.","vi":"Tôi đi tàu điện ngầm đi làm mỗi ngày."},{"cn":"坐地铁比开车快。","py":"Zuò dìtiě bǐ kāichē kuài.","vi":"Đi tàu điện ngầm nhanh hơn lái xe."}]'),
('公共汽车','公共汽車','gōng gòng qì chē','Xe buýt','Bus',1,'[{"cn":"我坐公共汽车上学。","py":"Wǒ zuò gōnggòng qìchē shàngxué.","vi":"Tôi đi xe buýt đến trường."}]'),
('骑车','騎車','qí chē','Đạp xe, đi xe đạp','To ride a bike',1,'[{"cn":"天气好的时候我喜欢骑车。","py":"Tiānqì hǎo de shíhòu wǒ xǐhuān qí chē.","vi":"Khi thời tiết đẹp tôi thích đạp xe."}]'),
('开车','開車','kāi chē','Lái xe ô tô','To drive',2,'[{"cn":"他每天开车上班。","py":"Tā měitiān kāichē shàngbān.","vi":"Anh ấy lái xe đi làm mỗi ngày."}]'),
('打电话','打電話','dǎ diàn huà','Gọi điện thoại','To make a phone call',1,'[{"cn":"我给他打了一个电话。","py":"Wǒ gěi tā dǎle yīgè diànhuà.","vi":"Tôi đã gọi điện cho anh ấy."},{"cn":"你可以打电话给我。","py":"Nǐ kěyǐ dǎ diànhuà gěi wǒ.","vi":"Bạn có thể gọi điện cho tôi."}]'),
('发短信','發短信','fā duǎn xìn','Nhắn tin','To send a text message',2,'[{"cn":"给我发短信就可以了。","py":"Gěi wǒ fā duǎnxìn jiù kěyǐ le.","vi":"Nhắn tin cho tôi là được rồi."}]'),
('上网','上網','shàng wǎng','Lên mạng, duyệt web','To go online',2,'[{"cn":"我喜欢上网查资料。","py":"Wǒ xǐhuān shàngwǎng chá zīliào.","vi":"Tôi thích lên mạng tra cứu thông tin."}]'),
('购物','購物','gòu wù','Mua sắm','Shopping',3,'[{"cn":"周末我和朋友一起去购物。","py":"Zhōumò wǒ hé péngyǒu yīqǐ qù gòuwù.","vi":"Cuối tuần tôi và bạn bè đi mua sắm cùng nhau."}]'),
('打折','打折','dǎ zhé','Giảm giá, khuyến mãi','Discount',2,'[{"cn":"这件衣服打八折。","py":"Zhè jiàn yīfú dǎ bā zhé.","vi":"Bộ áo này được giảm 20%."},{"cn":"现在打折，快去买吧！","py":"Xiànzài dǎzhé, kuài qù mǎi ba!","vi":"Đang giảm giá rồi, mau đi mua thôi!"}]'),
('便宜','便宜','pián yi','Rẻ','Cheap / Inexpensive',1,'[{"cn":"这家店的东西很便宜。","py":"Zhè jiā diàn de dōngxi hěn piányí.","vi":"Đồ ở cửa hàng này rất rẻ."},{"cn":"有没有便宜一点的？","py":"Yǒu méiyǒu piányí yīdiǎn de?","vi":"Có cái nào rẻ hơn không?"}]'),
('贵','貴','guì','Đắt, mắc','Expensive',1,'[{"cn":"这个包太贵了，我买不起。","py":"Zhège bāo tài guì le, wǒ mǎi bù qǐ.","vi":"Cái túi này đắt quá, tôi mua không nổi."}]'),
('天','天','tiān','Ngày, trời','Day / Sky',1,'[{"cn":"今天是个好天。","py":"Jīntiān shì gè hǎo tiān.","vi":"Hôm nay là một ngày đẹp."},{"cn":"天空很蓝。","py":"Tiānkōng hěn lán.","vi":"Bầu trời rất xanh."}]'),
('雨','雨','yǔ','Mưa','Rain',1,'[{"cn":"外面在下雨。","py":"Wàimiàn zài xià yǔ.","vi":"Bên ngoài đang mưa."},{"cn":"带把伞，天气预报说有雨。","py":"Dài bǎ sǎn, tiānqì yùbào shuō yǒu yǔ.","vi":"Mang ô theo đi, dự báo có mưa."}]'),
('热','熱','rè','Nóng','Hot',1,'[{"cn":"今天太热了！","py":"Jīntiān tài rè le!","vi":"Hôm nay nóng quá!"},{"cn":"夏天越南很热。","py":"Xiàtiān Yuènán hěn rè.","vi":"Mùa hè Việt Nam rất nóng."}]'),
('冷','冷','lěng','Lạnh','Cold',1,'[{"cn":"冬天这里很冷。","py":"Dōngtiān zhèlǐ hěn lěng.","vi":"Mùa đông ở đây rất lạnh."},{"cn":"你冷不冷？","py":"Nǐ lěng bu lěng?","vi":"Bạn có lạnh không?"}]'),
('春天','春天','chūn tiān','Mùa xuân','Spring',1,'[{"cn":"春天是我最喜欢的季节。","py":"Chūntiān shì wǒ zuì xǐhuān de jìjié.","vi":"Mùa xuân là mùa tôi thích nhất."}]'),
('夏天','夏天','xià tiān','Mùa hè','Summer',1,'[{"cn":"夏天我喜欢游泳。","py":"Xiàtiān wǒ xǐhuān yóuyǒng.","vi":"Mùa hè tôi thích đi bơi."}]'),
('秋天','秋天','qiū tiān','Mùa thu','Autumn / Fall',1,'[{"cn":"秋天的叶子很漂亮。","py":"Qiūtiān de yèzi hěn piàoliang.","vi":"Lá mùa thu rất đẹp."}]'),
('冬天','冬天','dōng tiān','Mùa đông','Winter',1,'[{"cn":"冬天我喜欢喝热汤。","py":"Dōngtiān wǒ xǐhuān hē rè tāng.","vi":"Mùa đông tôi thích uống canh nóng."}]'),

-- ========== Từ bổ sung cho 5 chủ đề mẫu HSK 1 ==========
-- Quốc gia
('日本','日本','rì běn','Nhật Bản','Japan',1,'[{"cn":"日本在中国的东边。","py":"Rìběn zài Zhōngguó de dōngbiān.","vi":"Nhật Bản ở phía đông của Trung Quốc."},{"cn":"我想去日本旅游。","py":"Wǒ xiǎng qù Rìběn lǚyóu.","vi":"Tôi muốn đi du lịch Nhật Bản."}]'),
('美国','美國','měi guó','Mỹ, Hoa Kỳ','United States',1,'[{"cn":"他在美国上大学。","py":"Tā zài Měiguó shàng dàxué.","vi":"Anh ấy học đại học ở Mỹ."},{"cn":"美国是一个很大的国家。","py":"Měiguó shì yīgè hěn dà de guójiā.","vi":"Mỹ là một đất nước rất lớn."}]'),
('英国','英國','yīng guó','Anh (nước)','United Kingdom',1,'[{"cn":"英国的首都是伦敦。","py":"Yīngguó de shǒudū shì Lúndūn.","vi":"Thủ đô của Anh là London."}]'),
('德国','德國','dé guó','Đức (nước)','Germany',1,'[{"cn":"德国的汽车很有名。","py":"Déguó de qìchē hěn yǒumíng.","vi":"Xe ô tô của Đức rất nổi tiếng."}]'),
('越南','越南','yuè nán','Việt Nam','Vietnam',1,'[{"cn":"越南的食物很好吃。","py":"Yuènán de shíwù hěn hǎochī.","vi":"Đồ ăn Việt Nam rất ngon."},{"cn":"我是越南人。","py":"Wǒ shì Yuènán rén.","vi":"Tôi là người Việt Nam."}]'),
-- duplicate: 认识
-- Số đếm
('零','零','líng','Số không','Zero',1,'[{"cn":"电话号码里有两个零。","py":"Diànhuà hàomǎ lǐ yǒu liǎng gè líng.","vi":"Số điện thoại có hai số không."},{"cn":"今天气温是零度。","py":"Jīntiān qìwēn shì líng dù.","vi":"Nhiệt độ hôm nay là 0 độ."}]'),
('个','個','gè','Cái, con, người (lượng từ chung)','(measure word)',1,'[{"cn":"我买了三个苹果。","py":"Wǒ mǎile sān gè píngguǒ.","vi":"Tôi mua ba quả táo."},{"cn":"她有两个孩子。","py":"Tā yǒu liǎng gè háizi.","vi":"Cô ấy có hai đứa con."}]'),
-- Mua sắm
('买','買','mǎi','Mua','To buy',1,'[{"cn":"我想买一件新衣服。","py":"Wǒ xiǎng mǎi yī jiàn xīn yīfú.","vi":"Tôi muốn mua một bộ quần áo mới."},{"cn":"你在哪里买的？","py":"Nǐ zài nǎlǐ mǎi de?","vi":"Bạn mua ở đâu vậy?"}]'),
('块','塊','kuài','Đồng (tiền tệ, Nhân dân tệ)','Yuan (currency)',1,'[{"cn":"这个苹果两块钱。","py":"Zhège píngguǒ liǎng kuài qián.","vi":"Quả táo này hai tệ."},{"cn":"一共多少块？","py":"Yīgòng duōshǎo kuài?","vi":"Tổng cộng bao nhiêu tệ?"}]'),
('衣服','衣服','yī fu','Quần áo','Clothes',1,'[{"cn":"这件衣服很漂亮。","py":"Zhè jiàn yīfú hěn piàoliang.","vi":"Bộ quần áo này rất đẹp."},{"cn":"我要换一件衣服。","py":"Wǒ yào huàn yī jiàn yīfú.","vi":"Tôi muốn thay một bộ quần áo."}]'),
-- Đồ dùng hàng ngày
('桌子','桌子','zhuō zi','Bàn','Table / Desk',1,'[{"cn":"书放在桌子上。","py":"Shū fàng zài zhuōzi shàng.","vi":"Sách đặt trên bàn."},{"cn":"这张桌子很大。","py":"Zhè zhāng zhuōzi hěn dà.","vi":"Cái bàn này rất to."}]'),
('椅子','椅子','yǐ zi','Ghế','Chair',1,'[{"cn":"请坐椅子。","py":"Qǐng zuò yǐzi.","vi":"Mời ngồi ghế."},{"cn":"那把椅子是新的。","py":"Nà bǎ yǐzi shì xīn de.","vi":"Cái ghế đó là mới."}]'),
-- Thú cưng
('叫','叫','jiào','Gọi, kêu, tên là','To call / be named',1,'[{"cn":"我的狗叫小黑。","py":"Wǒ de gǒu jiào Xiǎo Hēi.","vi":"Con chó của tôi tên là Tiểu Hắc."},{"cn":"你叫什么名字？","py":"Nǐ jiào shénmemíngzì?","vi":"Bạn tên là gì?"}]')

ON CONFLICT (simplified) DO UPDATE SET
  traditional = EXCLUDED.traditional,
  pinyin = EXCLUDED.pinyin,
  meaning_vi = EXCLUDED.meaning_vi,
  meaning_en = EXCLUDED.meaning_en,
  hsk_level = EXCLUDED.hsk_level,
  examples = EXCLUDED.examples;

-- Kết quả
SELECT hsk_level, COUNT(*) as total FROM vocabularies GROUP BY hsk_level ORDER BY hsk_level;
